events {}

http {
    upstream backend {
        server worker1:80;
        server worker2:80;
        server worker3:80;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://backend;
        }
    }
}